[package]
name = "adaptor"
version = "0.1.0"
edition = "2021"

[dependencies]
musig2 = "0.1.0"
secp = { version = "0.3", features = ["rand"]}
rand = { version = "0.8.5", default-features = false, features = ["std_rng"] }